services:
  astrbot:
    environment:
      - TZ=Asia/Shanghai
    image: soulter/astrbot:latest
    container_name: astrbot
    restart: always
    ports:
      - "6185:6185"
    volumes:
      - ./data:/AstrBot/data
      - ./napcat/napcat/config:/app/napcat/config
      - ./napcat/ntqq:/app/.config/QQ
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - astrbot
    cpus: 1.0
    mem_limit: 1g

networks:
  astrbot:
    external: true