services:
  wechatpadpro:
    image: luolinaiwis/wechatpadpro:latest
    container_name: wechatpadpro
    restart: unless-stopped
    ports:
      - "8059:8059"
    volumes:
      - ./wechatpadpro:/app
      - ./.env:/app/.env
    networks:
      - astrbot
    environment:
      - DEBUG=true
      - ADMIN_KEY=12345
      - REDIS_HOST=wechatpadpro_redis
      - REDIS_PASS=wechatpadpro_redis
      - MYSQL_CONNECT_STR=wechatpadpro:wechatpadpro_mysql@tcp(wechatpadpro_mysql:3306)/wechatpadpro?charset=utf8mb4&parseTime=true&loc=Local
      - PORT=8059
      - HOST=0.0.0.0
      - TZ=Asia/Shanghai
    depends_on:
      - wechatpadpro_mysql
      - wechatpadpro_redis

  wechatpadpro_redis:
    image: redis:7-alpine
    container_name: wechatpadpro_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf

#使用容器网络进行连接，无需映射端口
#    ports:
#      - "6379:6379"

    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - astrbot

  wechatpadpro_mysql:
    image: mysql:8.0
    container_name: wechatpadpro_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wechatpadpro_mysql
      - MYSQL_DATABASE=wechatpadpro
      - MYSQL_USER=wechatpadpro
      - MYSQL_PASSWORD=wechatpadpro_mysql

#使用容器网络进行连接，无需映射端口
#    ports:
#      - "3306:3306"

    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - astrbot
    command: --default-authentication-plugin=mysql_native_password

networks:
  astrbot:
    external: true
